### ISSUE TITLE
I found a possible bug

### ISSUE THREAD

**Issue by KEVAO28** [angela-d/abandoned-carts-opencart#12]
Hello, I found a possible bug (my opencart may be in trouble as well), when I select the request and click the button to send the email, I am redirected to the administrator login page and the message "Session token is invalid Please try again "I have reinstalled the module and I still get the same problem. link from the print screen below:

http://prntscr.com/j02622

Thank you for all the help you have given me.

**Comment by angela-d** [comment]
Definitely a bug!

Typo from the latest release - pushing out a fix momentarily!

Thanks for spotting it!!

**Comment by angela-d** [comment]
Bugfix committed to Github *and* Opencart :smiley:
