### ISSUE TITLE
I try to install and show a error: The file can not be found! Can you help me? Eu tentei instalar e me mostrou o seguinte erro: O arquivo não pode ser encontrado! Vocês podem me ajudar?

### ISSUE THREAD

**Issue by marcelo-ceschin-aptus** [angela-d/abandoned-carts-opencart#18]
I try to install and show a error: The file can not be found! Can you help me?
Eu tentei instalar e me mostrou o seguinte erro: O arquivo não pode ser encontrado! Vocês podem me ajudar?
Opencart 2.3.0.2

**Comment by angela-d** [comment]
Please post any error logs referencing the issue, from both:

`system/storage/logs/error.log`

and

`cpanel > Metrics > Errors`

If you are not on cpanel, then the system error logs in lieu of the cpanel logs.

**Comment by marcelo-ceschin-aptus** [comment]
error.log, just it:
2018-06-20 18:26:29 - PHP Notice:  Undefined variable: token in /home2/nabarbac/public_html/teste/admin/view/template/extension/module/quickcheckout.tpl on line 812
2018-06-20 18:26:29 - PHP Notice:  Undefined variable: token in /home2/nabarbac/public_html/teste/admin/view/template/extension/module/quickcheckout.tpl on line 909

In cpanel there is no errors

**Comment by marcelo-ceschin-aptus** [comment]
My Opencart version is 2.3.0,2

**Comment by angela-d** [comment]
That error is related to Quick Checkout, not Abandoned Carts.

What page are you accessing that says 'Cannot be found' and how did you install the plugin, originally?

**Comment by marcelo-ceschin-aptus** [comment]
There is no errors in log about Abandoned Carts. I can´t install the plugin on Installer. The error shows me there, on Installer.

**Comment by marcelo-ceschin-aptus** [comment]
![error_installer](https://user-images.githubusercontent.com/7014592/41678779-79b6ccfc-74a2-11e8-9425-ad4c342d74ef.jpg)
See the error, translating to english is: The file can not be found!

**Comment by angela-d** [comment]
Is your admin url something other than `/admin/` ?

**Comment by marcelo-ceschin-aptus** [comment]
site/teste/admin because it's a test shop. I already installed other plugins and it worked normal.

**Comment by marcelo-ceschin-aptus** [comment]
Is there a problem with this?

**Comment by angela-d** [comment]
No, that shouldn't matter so as long as your config.php reflects the path correctly.

A directory Abandoned Carts requires is not found, is my suspicion.

Make sure you have all of the following directories:
admin/controller/extension/module
admin/controller/report
admin/language
admin/model/extension/module
admin/view/template/extension/module
admin/view/template/report

Also worth mentioning: https://github.com/opencart/opencart/issues/1961

Specifically,
> are u sure you have the correct ftp permissions

from Daniel.

If you are working locally, there is a weird quirk in Open Cart 2.3.0.2 that requires FTP access, which you do not have when working local.

To get around that, use this extension:
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=18892

I just tested installing `abandoned-carts-v1.2.8.ocmod.zip` to a 2.3.0.2 test shop and it loaded without issue.

If you are using an RC (release candidate/beta version) of 2.3.0.2, this could be a cause of issues, too.

**Comment by marcelo-ceschin-aptus** [comment]
I've tried everything but nothing works

**Comment by marcelo-ceschin-aptus** [comment]
I found the problem, it was my config.php. Sorry for the inconvenience. Thanks for the extension.
